# The Importance of Vectorization

**Source (all credits to):** *Coursera: Neural Networks and Deep Learning Course*

# 1. Vectorization vs. dot/outer/elementwise product

## 1.1. Import libraries and Prepare Data

In [23]:
import time, numpy as np

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

## 1.2. Less efficient implementation - dot product of vectors

In [24]:
### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.process_time()
dot = 0

for i in range(len(x1)):
    dot += x1[i] * x2[i]
toc = time.process_time()

dot_time = (1000 * (toc - tic))
print ("Classic dot product of vectors = " + str(dot) + "\n\n ----- Computation time = " + str(dot_time) + "ms")

Classic dot product of vectors = 278

 ----- Computation time = 0.12490800000009017ms


## 1.3. Less efficient implementation - outer product

In [25]:
### CLASSIC OUTER PRODUCT IMPLEMENTATION ###
tic = time.process_time()
outer = np.zeros((len(x1), len(x2))) # we create a len(x1)*len(x2) matrix with only zeros

for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i] * x2[j]
toc = time.process_time()

outer_time = (1000 * (toc - tic))
print ("Classic outer product = " + str(outer) + "\n\n ----- Computation time = " + str(outer_time) + "ms")

Classic outer product = [[81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [63. 14. 14. 63.  0. 63. 14. 35.  0.  0. 63. 14. 35.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]

 ----- Computation time = 0.2

## 1.4. Less efficient implementation - elementwise product

In [26]:
### CLASSIC ELEMENTWISE IMPLEMENTATION ###
tic = time.process_time()
mul = np.zeros(len(x1))

for i in range(len(x1)):
    mul[i] = x1[i] * x2[i]
toc = time.process_time()

elementwise_time = (1000 * (toc - tic))
print ("Classic elementwise multiplication = " + str(mul) + "\n\n ----- Computation time = " + str(elementwise_time) + "ms")

Classic elementwise multiplication = [81.  4. 10.  0.  0. 63. 10.  0.  0.  0. 81.  4. 25.  0.  0.]

 ----- Computation time = 0.11009400000006053ms


## 1.5. Less efficient implementation - general dot product of vectors

In [27]:
### CLASSIC GENERAL DOT PRODUCT IMPLEMENTATION ###
W = np.random.rand(3,len(x1)) # Random 3*len(x1) numpy array
tic = time.process_time()
gdot = np.zeros(W.shape[0])

for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i,j] * x1[j]
toc = time.process_time()

gdot_time = (1000 * (toc - tic))
print ("Classic general dot product = " + str(gdot) + "\n\n ----- Computation time = " + str(gdot_time) + "ms")

Classic general dot product = [31.27306458 25.10692552 29.67773223]

 ----- Computation time = 0.14516599999980784ms


## 1.6. MORE efficient implementation - dot product vectorized

In [28]:
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()

vectorized_dot_time = (1000 * (toc - tic))
print ("dot vectorized = " + str(dot) + "\n\n ----- Computation time = " + str(vectorized_dot_time) + "ms")

dot vectorized = 278

 ----- Computation time = 0.08734700000001538ms


## 1.7. MORE efficient implementation - outer product vectorized

In [29]:
### VECTORIZED OUTER PRODUCT ###
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()

vectorized_outer_time = (1000 * (toc - tic))
print ("outer vectorized = " + str(outer) + "\n\n ----- Computation time = " + str(vectorized_outer_time) + "ms")

outer vectorized = [[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [63 14 14 63  0 63 14 35  0  0 63 14 35  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 ----- Computation time = 0.1046310000001327ms


## 1.8. MORE efficient implementation - elementwise product vectorized

In [30]:
### VECTORIZED ELEMENTWISE MULTIPLICATION ###
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()

vectorized_elementwise_time = (1000 * (toc - tic))
print ("elementwise vectorized = " + str(mul) + "\n\n ----- Computation time = " + str(vectorized_elementwise_time) + "ms")

elementwise vectorized = [81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]

 ----- Computation time = 0.07960500000026016ms


## 1.9. MORE efficient implementation - general dot product vectorized

In [31]:
### VECTORIZED GENERAL DOT PRODUCT ###
tic = time.process_time()
dot = np.dot(W,x1)
toc = time.process_time()

vectorized_gdot_time = (1000 * (toc - tic))
print ("general dot vectorized = " + str(dot) + "\n\n ----- Computation time = " + str(vectorized_gdot_time) + "ms")

general dot vectorized = [31.27306458 25.10692552 29.67773223]

 ----- Computation time = 0.09173300000009377ms


# 2. Final comparison

In [35]:
print('Classic dot product time = ' + str(dot_time))
print('Dot vectorized = ' + str(vectorized_dot_time))
print('---')
print('Classic outer product time = ' + str(outer_time))
print('Outer vectorized = ' + str(vectorized_outer_time))
print('---')
print('Classic elementwise product time = ' + str(elementwise_time))
print('Elementwise vectorized = ' + str(vectorized_elementwise_time))
print('---')
print('Classic general dot product time = ' + str(gdot_time))
print('General dot vectorized = ' + str(vectorized_gdot_time))

Classic dot product time = 0.12490800000009017
Dot vectorized = 0.08734700000001538
---
Classic outer product time = 0.24886600000018078
Outer vectorized = 0.1046310000001327
---
Classic elementwise product time = 0.11009400000006053
Elementwise vectorized = 0.07960500000026016
---
Classic general dot product time = 0.14516599999980784
General dot vectorized = 0.09173300000009377


**As you may have noticed, the vectorized implementation is much cleaner and more efficient. For bigger vectors/matrices, the differences in running time become even bigger.**